# Generated by Django 4.2.2 on 2023-07-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_info',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('employeename', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=50)),
                ('idcard', models.CharField(max_length=50)),
                ('birthday', models.DateTimeField()),
                ('hiredate', models.DateTimeField()),
                ('resigndate', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('createby', models.CharField(max_length=50)),
                ('updated', models.DateTimeField()),
                ('updateby', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='oldperson_info',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('oldname', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=50)),
                ('idcard', models.CharField(max_length=50)),
                ('birthday', models.DateTimeField()),
                ('checkindate', models.DateTimeField()),
                ('checkoutdate', models.DateTimeField()),
                ('roomnum', models.CharField(max_length=50)),
                ('firstguardianname', models.CharField(max_length=50)),
                ('firstguardianrela', models.CharField(max_length=50)),
                ('firstguardianphone', models.CharField(max_length=50)),
                ('firstguardianwechat', models.CharField(max_length=50)),
                ('secondguardianname', models.CharField(max_length=50)),
                ('secondguardianrela', models.CharField(max_length=50)),
                ('secondguardianphone', models.CharField(max_length=50)),
                ('secondguardianwechat', models.CharField(max_length=50)),
                ('healthstate', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('createby', models.CharField(max_length=50)),
                ('updated', models.DateTimeField()),
                ('updateby', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='volunteer_info',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('volunteername', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=50)),
                ('idcard', models.CharField(max_length=50)),
                ('birthday', models.DateTimeField()),
                ('checkindate', models.DateTimeField()),
                ('checkoutdate', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('createby', models.CharField(max_length=50)),
                ('updated', models.DateTimeField()),
                ('updateby', models.CharField(max_length=50)),
            ],
        ),
    ]
