# Generated by Django 4.2.2 on 2023-07-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementcenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='resigndate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='updateby',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='checkoutdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='updateby',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='checkoutdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='updateby',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
