# Generated by Django 4.2.2 on 2023-07-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementcenter', '0003_alter_employee_info_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='face_recognition_info',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('identity', models.CharField(max_length=50)),
                ('identity_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
