# Generated by Django 4.2.2 on 2023-07-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('realname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
