# Generated by Django 4.2.2 on 2023-07-05 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='ID',
        ),
    ]
