# Generated by Django 4.2.2 on 2023-07-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_info',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField()),
                ('event_desc', models.CharField(max_length=200)),
                ('oldperson_id', models.IntegerField()),
            ],
        ),
    ]
