# Generated by Django 4.2.2 on 2023-07-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caresystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_info',
            name='event_place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='oldperson_id',
            field=models.IntegerField(null=True),
        ),
    ]
